package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/naufalilyasa/pal-property-backend/internal/domain" // interface
	"github.com/naufalilyasa/pal-property-backend/internal/domain/entity"
	"gorm.io/gorm"
)

type authRepository struct {
	db *gorm.DB
}

func NewAuthRepository(db *gorm.DB) domain.AuthRepository {
	return &authRepository{db: db}
}

func (r *authRepository) FindOAuthAccount(ctx context.Context, provider, providerUserID string) (*entity.OAuthAccount, error) {
	var account entity.OAuthAccount
	err := r.db.WithContext(ctx).
		Where("provider = ? AND provider_user_id = ?", provider, providerUserID).
		First(&account).Error
	if err != nil {
		return nil, err
	}
	return &account, nil
}

func (r *authRepository) FindUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	var user entity.User
	err := r.db.WithContext(ctx).Where("email = ?", email).First(&user).Error
	if err != nil {
		return nil, err
	}
	return &user, nil
}

func (r *authRepository) FindUserByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	var user entity.User
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&user).Error
	if err != nil {
		return nil, err
	}
	return &user, nil
}

func (r *authRepository) CreateUserWithOAuth(ctx context.Context, user *entity.User, account *entity.OAuthAccount) (*entity.User, error) {
	return user, r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// 1. Create User
		if err := tx.Create(user).Error; err != nil {
			return err
		}

		// 2. Link OAuth Account (ID is generated by hook, but foreign key needs user ID)
		account.UserID = user.ID
		if err := tx.Create(account).Error; err != nil {
			return err
		}

		return nil
	})
}

func (r *authRepository) Updates(ctx context.Context, user *entity.User) error {
	return r.db.WithContext(ctx).Save(user).Error
}
