package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/naufalilyasa/pal-property-backend/internal/domain" // interface
	"github.com/naufalilyasa/pal-property-backend/internal/domain/entity"
	"github.com/naufalilyasa/pal-property-backend/pkg/config"
	"github.com/naufalilyasa/pal-property-backend/pkg/crypto"
	"gorm.io/gorm"
)

type authRepository struct {
	db *gorm.DB
}

func NewAuthRepository(db *gorm.DB) domain.AuthRepository {
	return &authRepository{db: db}
}

func (r *authRepository) FindOAuthAccount(ctx context.Context, provider, providerUserID string) (*entity.OAuthAccount, error) {
	var account entity.OAuthAccount
	err := r.db.WithContext(ctx).
		Where("provider = ? AND provider_user_id = ?", provider, providerUserID).
		First(&account).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domain.ErrNotFound
		}
		return nil, err
	}

	if account.AccessToken != nil {
		decrypted, err := crypto.Decrypt(*account.AccessToken, config.Env.OAuthTokenEncryptionKey)
		if err != nil {
			return nil, fmt.Errorf("repository: failed to decrypt access token: %w", err)
		}
		account.AccessToken = &decrypted
	}
	if account.RefreshToken != nil {
		decrypted, err := crypto.Decrypt(*account.RefreshToken, config.Env.OAuthTokenEncryptionKey)
		if err != nil {
			return nil, fmt.Errorf("repository: failed to decrypt refresh token: %w", err)
		}
		account.RefreshToken = &decrypted
	}
	return &account, nil
}

func (r *authRepository) FindUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	var user entity.User
	err := r.db.WithContext(ctx).Where("email = ?", email).First(&user).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domain.ErrNotFound
		}
		return nil, err
	}
	return &user, nil
}

func (r *authRepository) FindUserByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	var user entity.User
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&user).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domain.ErrNotFound
		}
		return nil, err
	}
	return &user, nil
}

func (r *authRepository) CreateUserWithOAuth(ctx context.Context, user *entity.User, account *entity.OAuthAccount) (*entity.User, error) {
	return user, r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// 1. Create User
		if err := tx.Create(user).Error; err != nil {
			return err
		}

		// 2. Link OAuth Account (ID is generated by hook, but foreign key needs user ID)
		account.UserID = user.ID

		if account.AccessToken != nil {
			encrypted, err := crypto.Encrypt(*account.AccessToken, config.Env.OAuthTokenEncryptionKey)
			if err != nil {
				return fmt.Errorf("repository: failed to encrypt access token: %w", err)
			}
			account.AccessToken = &encrypted
		}
		if account.RefreshToken != nil {
			encrypted, err := crypto.Encrypt(*account.RefreshToken, config.Env.OAuthTokenEncryptionKey)
			if err != nil {
				return fmt.Errorf("repository: failed to encrypt refresh token: %w", err)
			}
			account.RefreshToken = &encrypted
		}

		if err := tx.Create(account).Error; err != nil {
			return err
		}

		return nil
	})
}

func (r *authRepository) Updates(ctx context.Context, user *entity.User) error {
	return r.db.WithContext(ctx).Save(user).Error
}
