package postgres

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"unicode"
	"unicode/utf8"

	"github.com/google/uuid"
	"github.com/naufalilyasa/pal-property-backend/internal/domain" // interface
	"github.com/naufalilyasa/pal-property-backend/internal/domain/entity"
	"github.com/naufalilyasa/pal-property-backend/pkg/config"
	"github.com/naufalilyasa/pal-property-backend/pkg/crypto"
	"gorm.io/gorm"
)

type authRepository struct {
	db *gorm.DB
}

func NewAuthRepository(db *gorm.DB) domain.AuthRepository {
	return &authRepository{db: db}
}

func (r *authRepository) FindOAuthAccount(ctx context.Context, provider, providerUserID string) (*entity.OAuthAccount, error) {
	var account entity.OAuthAccount
	err := r.db.WithContext(ctx).
		Where("provider = ? AND provider_user_id = ?", provider, providerUserID).
		First(&account).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domain.ErrNotFound
		}
		return nil, err
	}

	account.AccessToken = decryptStoredOAuthToken(account.AccessToken, "access token")
	account.RefreshToken = decryptStoredOAuthToken(account.RefreshToken, "refresh token")
	return &account, nil
}

func (r *authRepository) FindUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	var user entity.User
	err := r.db.WithContext(ctx).Where("email = ?", email).First(&user).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domain.ErrNotFound
		}
		return nil, err
	}
	return &user, nil
}

func (r *authRepository) FindUserByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	var user entity.User
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&user).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domain.ErrNotFound
		}
		return nil, err
	}
	return &user, nil
}

func (r *authRepository) CreateUserWithOAuth(ctx context.Context, user *entity.User, account *entity.OAuthAccount) (*entity.User, error) {
	return user, r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// 1. Create User
		if err := tx.Create(user).Error; err != nil {
			return err
		}

		// 2. Link OAuth Account (ID is generated by hook, but foreign key needs user ID)
		account.UserID = user.ID
		if err := r.encryptOAuthTokens(account); err != nil {
			return err
		}

		if err := tx.Create(account).Error; err != nil {
			return err
		}

		return nil
	})
}

func (r *authRepository) CreateOAuthAccount(ctx context.Context, account *entity.OAuthAccount) error {
	if err := r.encryptOAuthTokens(account); err != nil {
		return err
	}

	return r.db.WithContext(ctx).Create(account).Error
}

func decryptOAuthToken(raw string, fieldName string) (*string, error) {
	decrypted, err := crypto.Decrypt(raw, config.Env.OAuthTokenEncryptionKey)
	if err == nil {
		return &decrypted, nil
	}
	if isLegacyPlaintextToken(raw, err) {
		plaintext := raw
		return &plaintext, nil
	}
	return nil, fmt.Errorf("repository: failed to decrypt %s: %w", fieldName, err)
}

func decryptStoredOAuthToken(raw *string, fieldName string) *string {
	if raw == nil {
		return nil
	}
	decrypted, err := decryptOAuthToken(*raw, fieldName)
	if err != nil {
		return nil
	}
	return decrypted
}

func isLegacyPlaintextToken(raw string, decryptErr error) bool {
	var corruptInputError base64.CorruptInputError
	if errors.As(decryptErr, &corruptInputError) {
		return isLikelyPlaintextToken([]byte(raw))
	}

	decoded, err := base64.URLEncoding.DecodeString(raw)
	if err != nil {
		return false
	}

	// Require the decoded bytes to look like plaintext before accepting them.
	return isLikelyPlaintextToken(decoded)
}

func isLikelyPlaintextToken(decoded []byte) bool {
	if len(decoded) == 0 || !utf8.Valid(decoded) {
		return false
	}

	for _, r := range string(decoded) {
		if unicode.IsControl(r) || unicode.IsSpace(r) {
			return false
		}
	}

	return true
}

func (r *authRepository) encryptOAuthTokens(account *entity.OAuthAccount) error {
	if account.AccessToken != nil {
		encrypted, err := crypto.Encrypt(*account.AccessToken, config.Env.OAuthTokenEncryptionKey)
		if err != nil {
			return fmt.Errorf("repository: failed to encrypt access token: %w", err)
		}
		account.AccessToken = &encrypted
	}
	if account.RefreshToken != nil {
		encrypted, err := crypto.Encrypt(*account.RefreshToken, config.Env.OAuthTokenEncryptionKey)
		if err != nil {
			return fmt.Errorf("repository: failed to encrypt refresh token: %w", err)
		}
		account.RefreshToken = &encrypted
	}
	return nil
}

func (r *authRepository) Updates(ctx context.Context, user *entity.User) error {
	return r.db.WithContext(ctx).Save(user).Error
}
