services:
  # 1. DATABASE UTAMA (PostgreSQL)
  postgres:
    image: postgres:17.8-alpine
    container_name: pal_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pal_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. CACHING & RATE LIMIT (Redis)
  redis:
    image: redis:8.2-alpine
    container_name: pal_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 3. MESSAGE BROKER (Redpanda)
  redpanda:
    image: redpandadata/redpanda:v25.3.9
    container_name: pal-redpanda
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --default-log-level=warn
    ports:
      - "19092:19092"   # Kafka-compatible external port
      - "18082:18082"   # Pandaproxy (REST proxy)
      - "18081:18081"   # Schema Registry
      - "9644:9644"     # Admin API
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  # 4. SEARCH ENGINE (Elasticsearch)
  elasticsearch:
    image: elasticsearch:8.19.11
    container_name: pal_elastic
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Matikan security SSL biar dev gampang
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Batasi RAM biar laptop gak meledak
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  # 5. BACKEND API (Golang)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pal_backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - redpanda
      - elasticsearch
    env_file:
      - ./backend/.env.docker 

volumes:
  postgres_data:
  redis_data:
  elastic_data:
  redpanda_data: