services:
  # 1. DATABASE UTAMA (PostgreSQL)
  postgres:
    image: postgres:17.8-alpine
    container_name: pal_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pal_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pal_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # 2. CACHING & RATE LIMIT (Redis)
  redis:
    image: redis:8.2-alpine
    container_name: pal_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 3. SEARCH ENGINE (Elasticsearch)
  elasticsearch:
    image: elasticsearch:8.19.11
    container_name: pal_elastic
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Matikan security SSL biar dev gampang
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Batasi RAM biar laptop gak meledak
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  # 4. BACKEND API (Golang)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pal_backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started
    env_file:
      - ./backend/.env.docker
    command: ["sh", "-c", "go run ./cmd/migrate/main.go && exec air"]

  listing-indexer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pal_listing_indexer
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    env_file:
      - ./backend/.env.docker
    command: ["sh", "-c", "go run ./cmd/listing-indexer"]

volumes:
  postgres_data:
  redis_data:
  elastic_data:
