// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/naufalilyasa/pal-property-backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// CreateUserWithOAuth provides a mock function with given fields: ctx, user, account
func (_m *AuthRepository) CreateUserWithOAuth(ctx context.Context, user *entity.User, account *entity.OAuthAccount) (*entity.User, error) {
	ret := _m.Called(ctx, user, account)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithOAuth")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User, *entity.OAuthAccount) (*entity.User, error)); ok {
		return rf(ctx, user, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User, *entity.OAuthAccount) *entity.User); ok {
		r0 = rf(ctx, user, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.User, *entity.OAuthAccount) error); ok {
		r1 = rf(ctx, user, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOAuthAccount provides a mock function with given fields: ctx, provider, providerUserID
func (_m *AuthRepository) FindOAuthAccount(ctx context.Context, provider string, providerUserID string) (*entity.OAuthAccount, error) {
	ret := _m.Called(ctx, provider, providerUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindOAuthAccount")
	}

	var r0 *entity.OAuthAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.OAuthAccount, error)); ok {
		return rf(ctx, provider, providerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.OAuthAccount); ok {
		r0 = rf(ctx, provider, providerUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OAuthAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, providerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *AuthRepository) FindUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByID provides a mock function with given fields: ctx, id
func (_m *AuthRepository) FindUserByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Updates provides a mock function with given fields: ctx, user
func (_m *AuthRepository) Updates(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Updates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
