// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// CacheRepository is an autogenerated mock type for the CacheRepository type
type CacheRepository struct {
	mock.Mock
}

// DeleteRefreshTokenJTI provides a mock function with given fields: ctx, jti
func (_m *CacheRepository) DeleteRefreshTokenJTI(ctx context.Context, jti string) error {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshTokenJTI")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveRefreshTokenJTI provides a mock function with given fields: ctx, jti, userID, expiration
func (_m *CacheRepository) SaveRefreshTokenJTI(ctx context.Context, jti string, userID uuid.UUID, expiration time.Duration) error {
	ret := _m.Called(ctx, jti, userID, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshTokenJTI")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, time.Duration) error); ok {
		r0 = rf(ctx, jti, userID, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateRefreshTokenJTI provides a mock function with given fields: ctx, jti, userID
func (_m *CacheRepository) ValidateRefreshTokenJTI(ctx context.Context, jti string, userID uuid.UUID) error {
	ret := _m.Called(ctx, jti, userID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshTokenJTI")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = rf(ctx, jti, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCacheRepository creates a new instance of CacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheRepository {
	mock := &CacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
