// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/naufalilyasa/pal-property-backend/internal/domain"
	entity "github.com/naufalilyasa/pal-property-backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ListingRepository is an autogenerated mock type for the ListingRepository type
type ListingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, listing
func (_m *ListingRepository) Create(ctx context.Context, listing *entity.Listing) (*entity.Listing, error) {
	ret := _m.Called(ctx, listing)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Listing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Listing) (*entity.Listing, error)); ok {
		return rf(ctx, listing)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Listing) *entity.Listing); ok {
		r0 = rf(ctx, listing)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Listing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Listing) error); ok {
		r1 = rf(ctx, listing)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateImage provides a mock function with given fields: ctx, image
func (_m *ListingRepository) CreateImage(ctx context.Context, image *entity.ListingImage) (*entity.ListingImage, error) {
	ret := _m.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for CreateImage")
	}

	var r0 *entity.ListingImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ListingImage) (*entity.ListingImage, error)); ok {
		return rf(ctx, image)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ListingImage) *entity.ListingImage); ok {
		r0 = rf(ctx, image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ListingImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.ListingImage) error); ok {
		r1 = rf(ctx, image)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ListingRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteImage provides a mock function with given fields: ctx, listingID, imageID
func (_m *ListingRepository) DeleteImage(ctx context.Context, listingID uuid.UUID, imageID uuid.UUID) error {
	ret := _m.Called(ctx, listingID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, listingID, imageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistsBySlug provides a mock function with given fields: ctx, slug
func (_m *ListingRepository) ExistsBySlug(ctx context.Context, slug string) (bool, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for ExistsBySlug")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ListingRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Listing, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Listing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Listing, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Listing); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Listing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindImageByID provides a mock function with given fields: ctx, id
func (_m *ListingRepository) FindImageByID(ctx context.Context, id uuid.UUID) (*entity.ListingImage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindImageByID")
	}

	var r0 *entity.ListingImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.ListingImage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.ListingImage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ListingImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySlug provides a mock function with given fields: ctx, slug
func (_m *ListingRepository) FindBySlug(ctx context.Context, slug string) (*entity.Listing, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *entity.Listing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Listing, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Listing); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Listing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *ListingRepository) FindByCategoryID(ctx context.Context, categoryID uuid.UUID) ([]*entity.Listing, error) {
	ret := _m.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCategoryID")
	}

	var r0 []*entity.Listing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Listing, error)); ok {
		return rf(ctx, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Listing); ok {
		r0 = rf(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Listing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: ctx, userID, filter
func (_m *ListingRepository) FindByUserID(ctx context.Context, userID uuid.UUID, filter domain.ListingFilter) ([]*entity.Listing, int64, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Listing
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ListingFilter) ([]*entity.Listing, int64, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ListingFilter) []*entity.Listing); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Listing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.ListingFilter) int64); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, domain.ListingFilter) error); ok {
		r2 = rf(ctx, userID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IncrementViewCount provides a mock function with given fields: ctx, id
func (_m *ListingRepository) IncrementViewCount(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementViewCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, filter
func (_m *ListingRepository) List(ctx context.Context, filter domain.ListingFilter) ([]*entity.Listing, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Listing
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListingFilter) ([]*entity.Listing, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListingFilter) []*entity.Listing); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Listing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListingFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.ListingFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListActiveImagesByListingID provides a mock function with given fields: ctx, listingID
func (_m *ListingRepository) ListActiveImagesByListingID(ctx context.Context, listingID uuid.UUID) ([]*entity.ListingImage, error) {
	ret := _m.Called(ctx, listingID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveImagesByListingID")
	}

	var r0 []*entity.ListingImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.ListingImage, error)); ok {
		return rf(ctx, listingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.ListingImage); ok {
		r0 = rf(ctx, listingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ListingImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, listingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReorderImages provides a mock function with given fields: ctx, listingID, orderedImageIDs
func (_m *ListingRepository) ReorderImages(ctx context.Context, listingID uuid.UUID, orderedImageIDs []uuid.UUID) error {
	ret := _m.Called(ctx, listingID, orderedImageIDs)

	if len(ret) == 0 {
		panic("no return value specified for ReorderImages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, listingID, orderedImageIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPrimaryImage provides a mock function with given fields: ctx, listingID, imageID
func (_m *ListingRepository) SetPrimaryImage(ctx context.Context, listingID uuid.UUID, imageID uuid.UUID) error {
	ret := _m.Called(ctx, listingID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for SetPrimaryImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, listingID, imageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, listing, fields
func (_m *ListingRepository) Update(ctx context.Context, listing *entity.Listing, fields []string) (*entity.Listing, error) {
	ret := _m.Called(ctx, listing, fields)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Listing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Listing, []string) (*entity.Listing, error)); ok {
		return rf(ctx, listing, fields)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Listing, []string) *entity.Listing); ok {
		r0 = rf(ctx, listing, fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Listing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Listing, []string) error); ok {
		r1 = rf(ctx, listing, fields)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewListingRepository creates a new instance of ListingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListingRepository {
	mock := &ListingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
