[request_definition]
r = sub, role, obj, act, owner

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = ((p.sub == r.role) || (p.sub == "owner" && r.sub == r.owner)) && r.obj == p.obj && r.act == p.act
